# Generated by Django 5.2.10 on 2026-02-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='insight',
            unique_together=set(),
        ),
    ]
