# Generated by Django 5.2.10 on 2026-02-04 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_alter_insight_options_alter_insight_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='month',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='year',
        ),
        migrations.AddField(
            model_name='insight',
            name='period_end',
            field=models.DateField(default=datetime.date(2026, 2, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insight',
            name='period_start',
            field=models.DateField(default=datetime.date(2026, 2, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insight',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
            preserve_default=False,
        ),
    ]
