# Generated by Django 5.2.10 on 2026-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_remove_insight_month_remove_insight_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='report_type',
            field=models.CharField(choices=[('analysis', 'Analysis')], max_length=10),
        ),
    ]
