# Generated by Codex on 2026-02-12

from django.db import migrations, models
from django.db.models import F, Q
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_alter_insight_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='created_at',
            field=models.DateTimeField(default=timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='insight',
            old_name='generated_at',
            new_name='updated_at',
        ),
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddConstraint(
            model_name='insight',
            constraint=models.CheckConstraint(
                condition=Q(period_end__gte=F('period_start')),
                name='insight_period_end_gte_start',
            ),
        ),
    ]
