# Generated by Codex on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_insight_created_updated_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
