# Generated by Django 5.2.10 on 2026-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_insight_created_updated_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='report_type',
            field=models.CharField(choices=[('analysis', 'Analysis')], max_length=50),
        ),
    ]
