# Generated by Django 5.2.10 on 2026-02-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0006_alter_insight_report_type'),
        ('insights', '0006_alter_insight_report_type_choices'),
    ]

    operations = [
    ]
