# Generated by Django 5.2.10 on 2026-02-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0007_merge_20260212_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50),
        ),
    ]
