# Generated by Django 5.2.7 on 2026-01-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_entry_duration_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='multiselect_value',
            field=models.JSONField(blank=True, help_text='Selected options as list', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='rating_value',
            field=models.IntegerField(blank=True, help_text='For rating tracker', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='text_value',
            field=models.TextField(blank=True, help_text='For text/notes tracker', null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Maximum rating value (e.g., 5 or 10)', null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Minimum rating value (e.g., 1)', null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='multiselect_options',
            field=models.JSONField(blank=True, help_text='List of options for multi-select', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_type',
            field=models.CharField(choices=[('binary', 'Yes/No (Binary)'), ('number', 'Number'), ('time', 'Time'), ('duration', 'Duration (Start/End Time)'), ('text', 'Text/Notes'), ('rating', 'Rating/Scale'), ('multiselect', 'Multi-Select')], max_length=20),
        ),
    ]
