# Generated by Django 5.2.7 on 2026-01-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_entry_multiselect_value_entry_rating_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='multiselect_value',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='multiselect_options',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_type',
            field=models.CharField(choices=[('binary', 'Yes/No (Binary)'), ('number', 'Number'), ('time', 'Time'), ('duration', 'Duration (Start/End Time)'), ('text', 'Text/Notes'), ('rating', 'Rating/Scale')], max_length=20),
        ),
    ]
