# Generated by Django 5.2.10 on 2026-02-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_entry_multiselect_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['display_order', 'created_at']},
        ),
    ]
