# Generated by Django 5.2.10 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_tracker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prayer_values',
            field=models.JSONField(blank=True, help_text='For prayer tracker', null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_type',
            field=models.CharField(choices=[('binary', 'Yes/No (Binary)'), ('number', 'Number'), ('time', 'Time'), ('duration', 'Duration (Start/End Time)'), ('text', 'Text/Notes'), ('rating', 'Rating/Scale'), ('prayer', 'Islamic Prayer (5x)')], max_length=20),
        ),
    ]
