# Generated by Django 5.2.7 on 2025-10-25 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tracker_type', models.CharField(choices=[('binary', 'Yes/No (Binary)'), ('number', 'Number'), ('time', 'Time'), ('duration', 'Duration (Start/End Time)')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('binary_value', models.BooleanField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_value', models.TimeField(blank=True, null=True)),
                ('duration_start', models.TimeField(blank=True, null=True)),
                ('duration_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tracker')),
            ],
            options={
                'unique_together': {('tracker', 'date')},
            },
        ),
    ]
