# Generated by Django 5.2.7 on 2026-01-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='duration_end',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='duration_start',
        ),
        migrations.AddField(
            model_name='entry',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
